### ISSUE TITLE
[DashboardEditor] card jumps when clicked

### ISSUE THREAD

**Issue by sstone2423** [carbon-design-system/carbon-addons-iot-react#1746] opened 2020-11-02 14:33 UTC
### What package is this for?

- [x] React
- [ ] Angular

### Describe the bug

When a card is clicked to be selected, it is also triggering the drag start effect created through react-grid-layout.

![card-click](https://user-images.githubusercontent.com/5167091/97689335-b2fb5180-1a9b-11eb-82be-9024cafa1582.gif)

### To Reproduce

1. Go to any DashboardEditor story 
2. Add a card
3. Click the card multiple times

### Expected behavior

The card should only move if the user's mouse begins to actually drag / move

### Environment/versions:

- OS: MacOS
- Browser: chrome
- `carbon-addons-iot-react` version: 2.140.0-next.7

### Specific timeline issues / requests

Do you want this work within a specific time period? Is it related to an
upcoming release?

No specific timeline

**Comment by tay1orjones** [comment] 2020-11-02 15:15
> it is also triggering the drag start effect created through react-grid-layout

That might be the cause of the movement too - I think rgl places a class on the element on drag, which could apply styles that cause the movement.

This all might be fixed by stopping the event propogation of a single non-drag click so it doesn't reach rgl.

**Comment by scottdickerson** [comment] 2021-02-01 23:28
this doesn't seem to be happening anymore

**Closed by scottdickerson** 2021-02-01 23:28 UTC
Labels: status: needs triage :mag:, type: bug :bug:
