### ISSUE TITLE
"Skip to main content" link is showing up with tab navigation on Hamburger

### ISSUE THREAD

**Issue by bakkireddi** [carbon-design-system/carbon-addons-iot-react#2123] opened 2021-03-16 13:24 UTC
As part of accessibility testing, when trying to click on the hamburger icon using the tab button "skip to main content" link is showing instead of the Hamburger icon in the browsers Chrome, Safari, Edge.
Please see the screenshot below.
<img width="971" alt="image" src="https://user-images.githubusercontent.com/37322952/111315832-c2fd8180-8688-11eb-81f9-8b96a2d3b439.png">
<img width="734" alt="image" src="https://user-images.githubusercontent.com/37322952/111315894-cf81da00-8688-11eb-8b3f-80e98a425df8.png">
<img width="628" alt="image" src="https://user-images.githubusercontent.com/37322952/111315971-ddcff600-8688-11eb-8bc3-4838d2c52df0.png">

**Comment by davidicus** [comment] 2021-04-01 15:34
This is intentionally the first thing that you can tab to. Pressing tab a second time will bring you to the hamburger menu. Closing as working as intended. Please feel free to reopen if you feel there is more to discuss.

**Closed by davidicus** 2021-04-01 15:34 UTC
Labels: status: needs triage :mag:, type: bug :bug:
