### ISSUE TITLE
long words not wrap in ProgressIndicator

### ISSUE THREAD

**Issue by yanzhe2017** [carbon-design-system/carbon-addons-iot-react#2090] opened 2021-03-04 15:42 UTC
I use ProgressIndicator, when switch to some language other than English, the translated word are long, it cannot be wrap.
Here is the issue
![image](https://user-images.githubusercontent.com/25318085/109988331-63c37700-7d42-11eb-95fc-a3400df652bc.png)

Here is my sample code:

<ProgressIndicator
                    currentItemId={currentItemId}
                    isClickable
                    isVerticalMode
                    items={TAB_ITEMS.map((tab, idx) => {
                      const tabItem = {
                        id: tab,
                        label:
                          g.id === undefined && idx === 0
                            ? intl.formatMessage({
                                id:
                                  'ui_defineGroup_title',
                              })
                            : intl.formatMessage({
                                id: 'ui_group_'.concat(
                                  tab,
                                  '_title'
                                ),
                              }),
                      };
                      if (idx === TAB_ITEMS.length - 1) {
                        tabItem.secondaryLabel = intl.formatMessage({
                          id: 'ui_optional_title',
                        });
                      }
                      return tabItem;
                    })}
                    onClickItem={this.onClickPageItem}
                    showLabels
                  />

**Comment by yanzhe2017** [comment] 2021-03-23 00:51
@sstone2423 @scottdickerson do you have follow up with this issue?

**Comment by davidicus** [comment] 2021-04-01 16:02
@yanzhe2017 It seems like the storybook is showing long titles being truncated with ellipsis. Can you verify that this is working for you?

![image](https://user-images.githubusercontent.com/1590966/113321967-1fe07500-92e2-11eb-9a5a-44164eb26930.png)

**Comment by yanzhe2017** [comment] 2021-04-02 01:05
Is this ellipsis introduced in latest build? which version I should use to test this?

**Comment by yanzhe2017** [comment] 2021-04-15 04:45
I make sure I use latest version, but same issue, the translation message is truncated.
+-- carbon-addons-iot-react@2.144.0
@davidicus where do you see the storybook of ellipsis effect?

**Comment by JordanWSmith15** [comment] 2021-07-28 18:15
Duplicate of #2605

**Closed by JordanWSmith15** 2021-07-28 18:15 UTC
Labels: severity: 3, type: bug :bug:
