### ISSUE TITLE
[table] Table always show 1000 total count even when the totalItems in pagination larger then 1000

### ISSUE THREAD

**Issue by zhaozhuo813** [carbon-design-system/carbon-addons-iot-react#1914] opened 2021-01-06 03:11 UTC
### What package is this for?

- [x] React
- [ ] Angular

### Describe the bug

When the totalItems in pagination larger then 1000,  e.g 2000 as following:
```
pagination: {
                          page: 1,
                          pageSize: this.state.pageSize,
                          pageSizes: [5, 10, 20, 30, 50],
                          totalItems: 2000
                        },
```
Then the total count is always displayed as 1000.  like below. 

<img width="1250" alt="image" src="https://user-images.githubusercontent.com/65387028/103724596-a9e4ae80-500f-11eb-89a6-f0f3fbf8cd80.png">

### Environment/versions:
- `carbon-addons-iot-react` version: [e.g. `v2.141.0`]

**Comment by davidicus** [comment] 2021-01-12 01:51
Hi @zhaozhuo813. I have looked into this issue and I have found the reason you for the 1000 item count. The table has a prop called maxPages found [here](https://github.com/carbon-design-system/carbon-addons-iot-react/blob/25009b4cffa4e7f9178fde76b6b38d9a442e1d97/src/components/Table/Table.jsx#L102). There are performance implications when loading the table with a high number of items and we have set the default to 1000. You can override this by changing the maxPages prop to whatever number you wish to show. (eg. `maxPages: 2000`). I have tested this out in our storybook and have confirmed that this will solve your issue. I am closing now but feel free to re-open if your issue still persist.

**Closed by davidicus** 2021-01-12 01:51 UTC
Labels: severity: 1 :rotating_light:, status: needs triage :mag:, type: bug :bug:

**Comment by tay1orjones** [comment] 2021-01-13 15:46
Related https://github.com/carbon-design-system/carbon-addons-iot-react/issues/458 https://github.com/carbon-design-system/carbon-addons-iot-react/pull/1208
