### ISSUE TITLE
[Dashboard] RTL is completely broken

### ISSUE THREAD

**Issue by stuckless** [carbon-design-system/carbon-addons-iot-react#637] opened 2019-10-25 19:39 UTC
### Describe the bug

Dashboard doesn't render correctly in RTL

### To Reproduce

Open the dashboard

1. Click RTL knob
2. Some things are pushed "right" but most coards are missing

### Expected behavior

Should basically be a mirror of the LTR mode

**Comment by JordanWSmith15** [comment] 2021-08-10 19:29
Duplicate of https://github.com/carbon-design-system/carbon-addons-iot-react/issues/1628

**Closed by JordanWSmith15** 2021-08-10 19:29 UTC
Labels: type: bug :bug:, type: RTL :arrow_left:, severity: 3
