### ISSUE TITLE
[SideNav] implementation QA

### ISSUE THREAD

**Issue by Ivan-Bachev** [carbon-design-system/carbon-addons-iot-react#1579] opened 2020-09-07 05:48 UTC
I am currently in a QA process of how the TRIRIGA designs we worked on are implemented. I noticed a couple of things in the SideNav component, and it looks like these are inherited from the Storybook code - https://carbon-addons-iot-react.com/?path=/story/watson-iot-sidenav--sidenav-component

1. There is an extra spacing above the first item in the implementation.

2. The icon size in the designed SideNav is 20x20px but in the implementation it looks like 16x16px

3. The 2nd level SideNav items are 32px heigh in the designs but implemented as 48px in the React code.

![PAL - SideNav - Design vs Implementation](https://user-images.githubusercontent.com/70877374/92352349-91f33180-f0e6-11ea-9103-0d516744ba0f.png)

**Comment by tay1orjones** [comment] 2020-09-22 22:01
Duplicate of #1618

**Comment by tay1orjones** [comment] 2020-09-22 22:02
There's a bit more detail reported in #1618 of the same items - closing in favor of tracking on that issue moving forward

**Closed by tay1orjones** 2020-09-22 22:02 UTC
Labels: status: needs triage :mag:, type: bug :bug:
