### ISSUE TITLE
[ProgressIndicator] The style with vertical presentation is incorrect on Chrome browser

### ISSUE THREAD

**Issue by xwgao** [carbon-design-system/carbon-addons-iot-react#2206] opened 2021-04-09 03:40 UTC
### What package is this for?

- [x] React
- [ ] Angular

### Describe the bug

The style of ProgressIndicator with vertical presentation is incorrect on Chrome browser.

### To Reproduce

When using ProgressIndicator with vertical presentation on **Chrome** browser, the style has some issue as below:

Link to storybook: https://carbon-addons-iot-react.com/?path=/story/watson-iot-progressindicator--presentation-vertical

![image](https://user-images.githubusercontent.com/54341035/114124882-f8b02600-9927-11eb-989f-6693d60a820c.png)

But it looks good on Firefox as below:

<img width="1275" alt="Screen Shot 2021-04-09 at 11 38 11 AM" src="https://user-images.githubusercontent.com/54341035/114124948-12ea0400-9928-11eb-8b51-13e6e860fc6b.png">

### Expected behavior

When using ProgressIndicator with vertical presentation on **Chrome** browser, the style looks good and same with that on Firefox.

### Environment/versions:

- OS: All
- Browser: Chrome Version 76.0.3809.132 (Official Build) (64-bit)
- `carbon-addons-iot-react` version: latest and earlier

**Comment by davidicus** [comment] 2021-04-09 13:40
Closing as a duplicate of #2129. This defect is not present in the latest version of Chrome. The version reported in this issue is 10+ major versions behind latest which is `89.0.4389.114`

**Closed by davidicus** 2021-04-09 13:40 UTC
Labels: status: needs triage :mag:, type: bug :bug:
