### ISSUE TITLE
[Table] Growing column width should not shrink next column

### ISSUE THREAD

**Issue by gillibrand** [carbon-design-system/carbon-addons-iot-react#2074] opened 2021-03-01 18:20 UTC
### What package is this for?

- [x] React
- [ ] Angular

### Summary

Please describe your request in one or two sentences.

When a table column is resized larger it shrinks the width of the next column. That is, the total width of the table never changes. This make it almost impossible for the user to get the columns to comfortable widths: fixing one destroys another. This is unlike most complicated tables, see Windows Explore details view, macOS Finder list view, Excel or any spreadsheet.

I can imagine some UIs with limited table space that might prefer the current pattern (possibly if there are only two columns in a small area), so the current pattern might need to be preserved (a prop to pick?). But the current pattern is unusable in most places in the ELM suite where many columns can be added to table and horizontal scrolling is OK. In many cases user can define their own columns, so the system has no idea what's a good size for their data. The user can just add some columns, look at them visually and resize them. But that's close to impossible with the current pattern.

Closely related to this is that the last column can't be resized "to the right" at all, unlike other columns. That means you can try to ripple the size changes manually from left to right, but once you hit the last column it will likely be tiny with no where to grow.

### Specific timeline issues / requests

Needed for work in ELM 7.0.3 release. Probably by June. We may have limited table adoption in this release, but this will eventually become a blocking issue.

### Available extra resources

Unclear. I've looked at the resize code, but may not have any time to allocate to this.

**Comment by JordanWSmith15** [comment] 2021-07-27 19:16
Closing this as a duplicate of #2471, and similar to #2460. We will be adding a property to the table that adds support for both horizontal scrolling and column resize.

**Closed by JordanWSmith15** 2021-07-27 19:16 UTC
Labels: offering: ELM, type: enhancement :bulb:, val: 3
