### ISSUE TITLE
[IconSwitch] After clicking on 'check more' carbon component button, the 'Switch to list' and 'Switch to floorplan' IconSwitch tooltips are not displayed when mouse hovered

### ISSUE THREAD

**Issue by AniruddChaturvedi** [carbon-design-system/carbon-addons-iot-react#2948] opened 2021-10-12 09:37 UTC
### What package is this for?

- [x] React
- [ ] Angular

### Describe the bug

Title. When we click on 'check more' carbon component button, the tooltip of 'Switch to list' & 'Switch to floorplan' IconSwitch  are not displayed when mouse is hover on them. This can be replicated in the https://appbuildapp.tririga-dev.com/reserve365ux/app/tririgaRoomReservation/.

### To Reproduce

1. Go to https://appbuildapp.tririga-dev.com/reserve365ux/app/tririgaRoomReservation/
2. Login to UX with the user created in pre requisite
3. Click on meeting room
4. Enter title, set date and time
5. Click on Rooms -> add building (select building which has more rooms)
6. Click on "Check more" button
7. Navigate and mouse hover on 'Switch to list' and 'Switch to floorplan'
8. Observe.

### Expected behavior

The tools tips of 'Switch to list' and 'Switch to floorplan' should be displayed when mouse hovered after clicking on 'check more' carbon component button.

### Environment/versions:

- OS: MacOS
- Browser: Chrome/Firefox/Safari
- carbon-addons-iot-react version: [e.g. v2.144.0]

### Additional context

Screenshot to understand the issue as after clicking on 'check more' button the tooltips of IconSwitch should be visible like this.

![image](https://user-images.githubusercontent.com/206663/94867040-46862780-03f5-11eb-859b-3b3a214c815e.png)

**Comment by JordanWSmith15** [comment] 2021-10-18 14:29
@AniruddChaturvedi I cannot access the environment to reproduce. Your 2nd step is
"Login to UX with the user created in pre requisite". That doesn't help much.

I was also unable to reproduce here:  
https://next.carbon-addons-iot-react.com/?path=/story/1-watson-iot-iconswitch--example-used-in-content-switcher-two-icons

**Comment by JordanWSmith15** [comment] 2021-10-19 17:02
@AniruddChaturvedi  A video may suffice for now. Can you take a video of your screen? Or, provide log-in credentials to the environment above?

**Comment by kevinsperrine** [comment] 2021-11-02 15:43
@AniruddChaturvedi Can you give me more details of your setup? What version of carbon-addons-iot-react are you using? I'm unable to recreate this using the newest `next` version. I tried using both sync and async callbacks on the button click.

![iconSwitch](https://user-images.githubusercontent.com/609466/139880401-7247f659-575d-4439-91e5-fd5008b81c5d.gif)

**Comment by AniruddChaturvedi** [comment] 2021-11-08 08:15
Hi @kevinsperrine , we are using below versions of carbon components -
 "carbon-addons-iot-react": "^2.144.0",
 "carbon-components": "^10.34.0",
 "carbon-components-react": "^7.34.0",

**Comment by kevinsperrine** [comment] 2021-11-08 13:58
Thanks, @AniruddChaturvedi. I can't pin point the exact commit, but this was fixed upstream by carbon (I believe in 10.36/7.36) which we pulled in and released in version v2.146.0-next.59, so anything newer than that should include this fix. You can see this was an issue with the ContentSwitch in this deploy preview (when we [upgraded to 10.31/7.31](https://deploy-preview-2190--carbon-addons-iot-react.netlify.app/?path=/story/watson-iot-iconswitch--example-used-in-content-switcher)), but disappears later during the next [carbon upgrade PR](https://deploy-preview-2515--carbon-addons-iot-react.netlify.app/?path=/story/1-watson-iot-iconswitch--example-used-in-content-switcher) that jumped all the way to 10.39/7.39. Please LMK if you're still having this problem after the upgrade and we'll re-open this issue and dig in more. BTW, the sandbox link is fixed in newer versions, too, so you can use that to re-create the issue if it persists. 

https://codesandbox.io/s/github/carbon-design-system/carbon-addons-iot-react/tree/next/packages/react/examples/codesandbox

**Closed by kevinsperrine** 2021-11-08 13:58 UTC
Labels: type: bug :bug:, severity: 3, status: waiting for author's response 💬, status: needs triage :mag:, package: react
