### ISSUE TITLE
[build] Build pipeline for PRs should create a production build of an application

### ISSUE THREAD

**Issue by stuckless** [carbon-design-system/carbon-addons-iot-react#2776] opened 2021-08-29 11:49 UTC
### What package is this for?

- [X ] React
- [ ] Angular

### Summary

As part of the PR build pipeline, there should be a sample app that uses the PAL components.  This app should consume the PAL components as a downstream consumer would do, and create a production build of the application to verify that the entire end to end build pipeline will continue to work with this new build of the components.

**Comment by kevinsperrine** [comment] 2021-08-30 18:39
duplicate of https://github.com/carbon-design-system/carbon-addons-iot-react/issues/1730.

**Closed by kevinsperrine** 2021-08-30 18:39 UTC
Labels: type: enhancement :bulb:, status: needs triage :mag:, status: needs priority :inbox_tray:
