### ISSUE TITLE
[PAL Table] Process related Console errors while accessing PAL tables

### ISSUE THREAD

**Issue by kshiti-p** [carbon-design-system/carbon-addons-iot-react#3426] opened 2022-04-29 09:43 UTC
### What package is this for?

- [x] React
- [ ] Angular

### Describe the bug
Process related Console errors while Sorting, Row click, Row expand in PAL table, though the functionalities work fine.

### To Reproduce
PAL Table > Stateful Table > Click on any column for sorting
PAL Table > Nested Rows Table > Click on down key arrow to collapse
PAL Table > Large Table > Click on any row

Console Errors when reproduced
![console_error](https://user-images.githubusercontent.com/103924274/165921437-32bd70c8-415d-4857-8709-0e2339da2ce9.png)

### Expected behavior
Functionalities works fine, console needs to get rid of the warnings and errors

**Comment by davidicus** [comment] 2022-05-16 14:37
Closing as we are unable to reproduce. Please re-open if you feel like this is still an issue.

**Closed by davidicus** 2022-05-16 14:37 UTC
Labels: type: bug :bug:, severity: 1 :rotating_light:, status: waiting for author's response 💬
