### ISSUE TITLE
[Table]: Row Actions how should they work with horizontal scrolling?

### ISSUE THREAD

**Issue by scottdickerson** [carbon-design-system/carbon-addons-iot-react#127] opened 2019-04-01 21:50 UTC

**Comment by matsgothe** [comment] 2019-04-02 07:53
This design should clarify the behavior of row and bulk action presentation on rows with column width that is wider than the table width, hence requiring horizontal scrolling to 'see' the right edge of the row.

Design proposal.
- Today, table paging controls and table bulk actions are presented with the visible width of the table.
- The row action controls today are presented at the far right edge of the total width of the row.
- A change request may be raised to change the behavior to allocation space to the right edge of the visible table to show the row controls regardless of horizontal scroll.
- The row action space would overlay, or preferable shrink the width on the rightmost column of the row. Hence, moving the mouse over rows with not change the overall column width layout, but only shorten the width of the currently hovered row to show the action controls to the right.
- Likewise, there would also be a similar space to the left showing row state and progress.

**Comment by matsgothe** [comment] 2019-04-02 07:53
Assigning to Amy for visual design considerations and alternative proposals.

**Comment by amymillett** [comment] 2019-04-09 22:08
I want to hear Cynthia's thoughts here (can we add her to this repo?), but I think @matsgothe's design proposal above makes sense.

Instead of appending the row actions to the far right side of the table and making the user scroll to see them, the actions would always appear to the right of the visible window, regardless of scrolling. This would probably mean that we need to allocate a certain amount of space to the right side of the viewing window to always be reserved for the row actions. 

Maybe we can consider the row actions as their own column that's always fixed on the right side of the visible screen. The Carbon X kit has actually introduced something similar called an icon column:

<img width="1040" alt="Screen Shot 2019-04-09 at 4 54 51 PM" src="https://user-images.githubusercontent.com/48336859/55837879-40f19f00-5ae8-11e9-8277-4b133a48cfa9.png">

**Comment by scottdickerson** [comment] 2019-04-29 14:49
need to check how carbon did it but this looks good thanks!

**Comment by scottdickerson** [comment] 2019-04-29 15:01
If we're able to implement this in a way that would also address the left panel fixed this would be great! Perhaps a column prop that fixed to left or right

**Comment by davidicus** [comment] 2020-06-02 15:26
This issue is stale. Closing. Please re-open if needed.

**Comment by matsgothe** [comment] 2020-06-04 07:57
My vote on this to be a table feature to resolve. There is a design to implement.

**Comment by CynZhang** [comment] 2020-06-04 13:37
We actually need to fix this issue now. The overflow button is now hard to discover without scrolling. I think Amy's suggestion of keeping an icon column fixed on the right to keep it visible is doable. Generally we want to keep the row options (icons, or text) to no more than 3 items. So the width of the icon column is within a certain range that should not require a lot of space.

Overflow button is hidden 
<img width="1594" alt="image" src="https://user-images.githubusercontent.com/46002772/83762429-830f6580-a645-11ea-961f-d9f35b38e642.png">

Overflow button appears after scrolling 
<img width="1597" alt="image" src="https://user-images.githubusercontent.com/46002772/83762451-8c98cd80-a645-11ea-8dc2-b2866f0d9569.png">

**Comment by matsgothe** [comment] 2020-06-08 06:45
@amymillett FYI.

**Comment by davidicus** [comment] 2021-07-23 15:26
closing as dupe of #1043

**Closed by davidicus** 2021-07-23 15:26 UTC
Labels: offering: health, offering: platform/monitor, type: help wanted :open_hands:, val: 3
